/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mizanreport;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;
import javax.swing.event.MouseInputListener;

/**
 *
 * @author Minami
 */
public class Mainview extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu
     */
    public Mainview() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_atas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_bawah = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        mainpane = new javax.swing.JPanel();
        paksikeuangan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lkeuangan = new javax.swing.JLabel();
        pkeuangan = new javax.swing.JPanel();
        llaporannama = new javax.swing.JLabel();
        paksibukubesar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbukubesar = new javax.swing.JLabel();
        pbukubesar = new javax.swing.JPanel();
        paksipembelian = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lpembelian = new javax.swing.JLabel();
        ppembelian = new javax.swing.JPanel();
        paksipenjualan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lpenjualan = new javax.swing.JLabel();
        ppenjualan = new javax.swing.JPanel();
        paksipersediaan = new javax.swing.JPanel();
        llainnyas = new javax.swing.JLabel();
        lpersediaan = new javax.swing.JLabel();
        ppersediaan = new javax.swing.JPanel();
        paksilainya = new javax.swing.JPanel();
        llainnyas1 = new javax.swing.JLabel();
        llainnya = new javax.swing.JLabel();
        plainnya = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mizanpost");
        setBackground(new java.awt.Color(255, 255, 255));

        panel_atas.setBackground(new java.awt.Color(41, 39, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Laporan");

        javax.swing.GroupLayout panel_atasLayout = new javax.swing.GroupLayout(panel_atas);
        panel_atas.setLayout(panel_atasLayout);
        panel_atasLayout.setHorizontalGroup(
            panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_atasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_atasLayout.setVerticalGroup(
            panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_atasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panel_bawah.setBackground(new java.awt.Color(41, 39, 40));

        javax.swing.GroupLayout panel_bawahLayout = new javax.swing.GroupLayout(panel_bawah);
        panel_bawah.setLayout(panel_bawahLayout);
        panel_bawahLayout.setHorizontalGroup(
            panel_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        panel_bawahLayout.setVerticalGroup(
            panel_bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(41, 39, 40));
        jPanel5.setForeground(new java.awt.Color(41, 39, 40));

        mainpane.setBackground(new java.awt.Color(255, 255, 255));
        mainpane.setLayout(new java.awt.BorderLayout());

        paksikeuangan.setBackground(new java.awt.Color(41, 39, 40));
        paksikeuangan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Keuangan");

        lkeuangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lkeuangan.setForeground(new java.awt.Color(255, 255, 255));
        lkeuangan.setText("V");

        javax.swing.GroupLayout paksikeuanganLayout = new javax.swing.GroupLayout(paksikeuangan);
        paksikeuangan.setLayout(paksikeuanganLayout);
        paksikeuanganLayout.setHorizontalGroup(
            paksikeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksikeuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lkeuangan)
                .addContainerGap())
        );
        paksikeuanganLayout.setVerticalGroup(
            paksikeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksikeuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paksikeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lkeuangan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pkeuangan.setBackground(new java.awt.Color(255, 255, 255));

        llaporannama.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        llaporannama.setText("Laporan Data Nama");

        javax.swing.GroupLayout pkeuanganLayout = new javax.swing.GroupLayout(pkeuangan);
        pkeuangan.setLayout(pkeuanganLayout);
        pkeuanganLayout.setHorizontalGroup(
            pkeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkeuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(llaporannama)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pkeuanganLayout.setVerticalGroup(
            pkeuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkeuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(llaporannama)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        paksibukubesar.setBackground(new java.awt.Color(41, 39, 40));
        paksibukubesar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buku Besar");

        lbukubesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbukubesar.setForeground(new java.awt.Color(255, 255, 255));
        lbukubesar.setText("V");

        javax.swing.GroupLayout paksibukubesarLayout = new javax.swing.GroupLayout(paksibukubesar);
        paksibukubesar.setLayout(paksibukubesarLayout);
        paksibukubesarLayout.setHorizontalGroup(
            paksibukubesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksibukubesarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbukubesar)
                .addContainerGap())
        );
        paksibukubesarLayout.setVerticalGroup(
            paksibukubesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksibukubesarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paksibukubesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbukubesar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pbukubesar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pbukubesarLayout = new javax.swing.GroupLayout(pbukubesar);
        pbukubesar.setLayout(pbukubesarLayout);
        pbukubesarLayout.setHorizontalGroup(
            pbukubesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pbukubesarLayout.setVerticalGroup(
            pbukubesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        paksipembelian.setBackground(new java.awt.Color(41, 39, 40));
        paksipembelian.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pembelian & Hutang");

        lpembelian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lpembelian.setForeground(new java.awt.Color(255, 255, 255));
        lpembelian.setText("V");

        javax.swing.GroupLayout paksipembelianLayout = new javax.swing.GroupLayout(paksipembelian);
        paksipembelian.setLayout(paksipembelianLayout);
        paksipembelianLayout.setHorizontalGroup(
            paksipembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksipembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(lpembelian)
                .addContainerGap())
        );
        paksipembelianLayout.setVerticalGroup(
            paksipembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksipembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paksipembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lpembelian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ppembelian.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ppembelianLayout = new javax.swing.GroupLayout(ppembelian);
        ppembelian.setLayout(ppembelianLayout);
        ppembelianLayout.setHorizontalGroup(
            ppembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ppembelianLayout.setVerticalGroup(
            ppembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        paksipenjualan.setBackground(new java.awt.Color(41, 39, 40));
        paksipenjualan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Penjualan & Piutang");

        lpenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lpenjualan.setForeground(new java.awt.Color(255, 255, 255));
        lpenjualan.setText("V");

        javax.swing.GroupLayout paksipenjualanLayout = new javax.swing.GroupLayout(paksipenjualan);
        paksipenjualan.setLayout(paksipenjualanLayout);
        paksipenjualanLayout.setHorizontalGroup(
            paksipenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksipenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lpenjualan)
                .addContainerGap())
        );
        paksipenjualanLayout.setVerticalGroup(
            paksipenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksipenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paksipenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lpenjualan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ppenjualan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ppenjualanLayout = new javax.swing.GroupLayout(ppenjualan);
        ppenjualan.setLayout(ppenjualanLayout);
        ppenjualanLayout.setHorizontalGroup(
            ppenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ppenjualanLayout.setVerticalGroup(
            ppenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        paksipersediaan.setBackground(new java.awt.Color(41, 39, 40));
        paksipersediaan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        llainnyas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        llainnyas.setForeground(new java.awt.Color(255, 255, 255));
        llainnyas.setText("Persediaan");

        lpersediaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lpersediaan.setForeground(new java.awt.Color(255, 255, 255));
        lpersediaan.setText("V");

        javax.swing.GroupLayout paksipersediaanLayout = new javax.swing.GroupLayout(paksipersediaan);
        paksipersediaan.setLayout(paksipersediaanLayout);
        paksipersediaanLayout.setHorizontalGroup(
            paksipersediaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksipersediaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(llainnyas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(lpersediaan)
                .addContainerGap())
        );
        paksipersediaanLayout.setVerticalGroup(
            paksipersediaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksipersediaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paksipersediaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llainnyas)
                    .addComponent(lpersediaan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ppersediaan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ppersediaanLayout = new javax.swing.GroupLayout(ppersediaan);
        ppersediaan.setLayout(ppersediaanLayout);
        ppersediaanLayout.setHorizontalGroup(
            ppersediaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ppersediaanLayout.setVerticalGroup(
            ppersediaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        paksilainya.setBackground(new java.awt.Color(41, 39, 40));
        paksilainya.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        llainnyas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        llainnyas1.setForeground(new java.awt.Color(255, 255, 255));
        llainnyas1.setText("Lainnya");

        llainnya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        llainnya.setForeground(new java.awt.Color(255, 255, 255));
        llainnya.setText("V");

        javax.swing.GroupLayout paksilainyaLayout = new javax.swing.GroupLayout(paksilainya);
        paksilainya.setLayout(paksilainyaLayout);
        paksilainyaLayout.setHorizontalGroup(
            paksilainyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksilainyaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(llainnyas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(llainnya)
                .addContainerGap())
        );
        paksilainyaLayout.setVerticalGroup(
            paksilainyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paksilainyaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paksilainyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llainnyas1)
                    .addComponent(llainnya))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plainnya.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout plainnyaLayout = new javax.swing.GroupLayout(plainnya);
        plainnya.setLayout(plainnyaLayout);
        plainnyaLayout.setHorizontalGroup(
            plainnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        plainnyaLayout.setVerticalGroup(
            plainnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paksipersediaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ppenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paksipenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ppembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paksipembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbukubesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paksibukubesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pkeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paksikeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ppersediaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paksilainya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plainnya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(mainpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(paksikeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pkeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paksibukubesar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pbukubesar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paksipembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ppembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paksipenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ppenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paksipersediaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ppersediaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paksilainya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(plainnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_atas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panel_bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel lbukubesar;
    public javax.swing.JLabel lkeuangan;
    public javax.swing.JLabel llainnya;
    private javax.swing.JLabel llainnyas;
    private javax.swing.JLabel llainnyas1;
    public javax.swing.JLabel llaporannama;
    public javax.swing.JLabel lpembelian;
    public javax.swing.JLabel lpenjualan;
    public javax.swing.JLabel lpersediaan;
    public javax.swing.JPanel mainpane;
    public javax.swing.JPanel paksibukubesar;
    public javax.swing.JPanel paksikeuangan;
    public javax.swing.JPanel paksilainya;
    public javax.swing.JPanel paksipembelian;
    public javax.swing.JPanel paksipenjualan;
    public javax.swing.JPanel paksipersediaan;
    private javax.swing.JPanel panel_atas;
    private javax.swing.JPanel panel_bawah;
    public javax.swing.JPanel pbukubesar;
    public javax.swing.JPanel pkeuangan;
    public javax.swing.JPanel plainnya;
    public javax.swing.JPanel ppembelian;
    public javax.swing.JPanel ppenjualan;
    public javax.swing.JPanel ppersediaan;
    // End of variables declaration//GEN-END:variables
}
